using System;
using System.Collections.Generic;
using System.IO;
using ProjectReconstructor.Extensions;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Xml.Linq;
using Microsoft.Build.Evaluation;
//using Microsoft.CodeAnalysis.Operations;
using Microsoft.CodeAnalysis;
using ProjectReconstructor.Domain;

namespace ProjectReconstructor
{
    public class MksProjectFile
    {


        #region Props

        /// <summary>
        /// This is the path relative to the new solutionfile
        /// </summary>
        public string RelativePath { get; set; }

        /// <summary>
        /// This is the absolute path to the target
        /// </summary>
        public string AbsoluteTargetPath { get; set; }

        public string AbsoluteSourePath { get; set; }
        /// <summary>
        /// The guid of the file
        /// </summary>
        public string Guid { get; set; }

        //the root name space of this project
        public string NameSpace { get; set; }
        /// <summary>
        /// This is the name of the csproj file without the .csproj name
        /// 
        /// </summary>
        public string Name { get; set; }

        /// <summary>
        /// This is the name of the file. ex: foo.csproj
        /// </summary>
        public string FileName { get; set; }

        public string XML { get; set; }

        /// <summary>
        /// this is a string list of al the references we think should be contained
        /// generated by scanning all the files of the project
        /// </summary>
        public string[] References { get; set; }

        /// <summary>
        /// this is a string list of all the namespaces contained in the project
        /// </summary>
        public string[] NameSpaces { get; set; }

        /// <summary>
        /// These are the raw Project Items that are grouped into this project
        /// file.
        /// </summary>
        public IEnumerable<MksProjectItem> ProjectItems { get; set; }

        #endregion


        public MksProjectFile()
        {

        }



        //public MksProjectFile(string directoryPath, string nameToUSe)
        //{

        //    ProjectItems = projectItems;

        //    References = 
        //}


        protected bool Equals(MksProjectFile other)
        {
            return string.Equals(RelativePath, other.RelativePath);
        }

        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            if (obj.GetType() != this.GetType()) return false;
            return Equals((MksProjectFile) obj);
        }

        public override int GetHashCode()
        {
            return (RelativePath != null ? RelativePath.GetHashCode() : 0);
        }
    }
}
